define({
  "name": "Tài liệu thiết kế API cho website Bách Hóa Xanh",
  "version": "1.0.0",
  "description": "bachhoaxanh.com",
  "title": "Bách Hóa Xanh",
  "url": "https://www.bachhoaxanh.com/api/v1",
  "sampleUrl": null,
  "order": [
    "Khách_hàng",
    "Đăng_ký",
    "Đăng_nhập",
    "Cập_nhật_thông_tin",
    "Đổi_mật_khẩu",
    "Lịch_sử_tìm_kiếm",
    "Sản_phẩm",
    "Lấy_danh_mục_sản_phẩm",
    "Lấy_danh_sách_nhóm_sản_phẩm",
    "Lấy_danh_sách_thương_hiệu",
    "Lấy_danh_sách_sản_phẩm",
    "Lấy_thông_tin_sản_phẩm",
    "Bình_luận_đánh_giá",
    "Gửi_bình_luận_đánh_giá",
    "Lấy_bình_luận_đánh_giá",
    "Khuyến_mãi",
    "Số_lượng_khuyến_mãi",
    "Quảng_cáo",
    "Lấy_quảng_cáo",
    "Địa_chỉ",
    "Lấy_danh_sách_khu_vực",
    "Giỏ_hàng",
    "Thêm_sản_phẩm",
    "Xóa_sản_phẩm",
    "Cập_nhật_số_lượng",
    "Xem_giỏ_hàng",
    "Xóa_giỏ_hàng",
    "Đơn_hàng",
    "Tạo_đơn_hàng",
    "Hủy_đơn_hàng",
    "Mẹo_vặt",
    "Xem_danh_sách_bài_viết",
    "Xem_bài_viết"
  ],
  "defaultVersion": "0.0.0",
  "apidoc": "0.3.0",
  "generator": {
    "name": "apidoc",
    "time": "2021-07-03T11:59:18.385Z",
    "url": "https://apidocjs.com",
    "version": "0.28.1"
  }
});
